version: "3.9"
services:

 servernode:
  build: .
  restart: always
  ports:
   - "80:3000"
  links:
   - monguitodb
  volumes:
   - ./:/code

 monguitodb:
  image: mongo:bionic
  ports:
   - "27017:27017"
  volumes:
   - mongo-data:/data/db

volumes:
 mongo-data:

